#template: Hello, %s!
#defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings.
database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:~/money;DB_CLOSE_ON_EXIT=FALSE
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true
    hibernate.hbm2ddl.import_files: init.sql

# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
